coder/images

- README.md
As of 1.6.0, multi-editor was promoted from alpha to beta and many of the aforementioned known issues have been addressed
> Update feature status, known issues

- images/node/Dockerfile.centos
- images/node/Dockerfile.ubuntu
Adds images for OOTB images that come with NodeJS LTS and Yarn installed.
> Add node default images

- LICENSE.md
This PR includes an MIT license, as well as an addendum detailing the additional license requirements users may encounter.
> Add license.

- images/golang/Dockerfile.centos
- images/golang/Dockerfile.ubuntu
Grabs go 1.15.3, sets up PATH and GOROOT. Not sure if there's anything else we should be doing.
> Add golang default images

- images/node/Dockerfile.ubuntu
> Run update after adding yarn source

- .github/CONTRIBUTING.md
- README.md
> Create contributing document

- bin/push-images.sh
Looks like some lingering lines from `build-images.sh`
> Refactor push-images

- images/base/Dockerfile.ubuntu
> feat(base): Ubuntu git-core ppa

- images/vnc/Dockerfile.ubuntu
- scripts/images.sh
this branch will be used to test CI on the VNC image
> add CI for VNC image

- images/vnc/README.md
@bpmct this adds the link to the Dockerhub as we discussed
> Add Dockerhub link to README

- images/dataSpell/Dockerfile.centos
- images/dataSpell/Dockerfile.ubuntu
adding the official DataSpell image for Coder. tested & validated on master:
I'll add the centOS version shortly.
> add DataSpell image

- images/base/Dockerfile.arch
- images/base/Dockerfile.centos
- images/base/Dockerfile.ubuntu
[ch13825]
Tested on Ubuntu, Centos, and Alpine with this sample project: https://github.com/docker/awesome-compose/tree/master/nginx-golang
> add docker-compose to base images

- images/jupyter/Dockerfile.centos
- images/jupyter/Dockerfile.ubuntu
let me know if I understood the ask correctly. thanks @jawnsy.
> update jupyter images w/ latest core version

- images/android/Dockerfile.ubuntu
- images/base/Dockerfile.arch
- images/base/Dockerfile.centos
- images/base/Dockerfile.ubuntu
- images/clion/Dockerfile.centos
- images/clion/Dockerfile.ubuntu
- images/dataSpell/Dockerfile.centos
- images/dataSpell/Dockerfile.ubuntu
- images/goland/Dockerfile.centos
- images/goland/Dockerfile.ubuntu
- images/golang/Dockerfile.centos
- images/golang/Dockerfile.ubuntu
- images/intellij/Dockerfile.centos
- images/intellij/Dockerfile.ubuntu
- images/java/Dockerfile.centos
- images/java/Dockerfile.ubuntu
- images/jupyter/Dockerfile.centos
- images/jupyter/Dockerfile.ubuntu
- images/multieditor/Dockerfile.centos
- images/multieditor/Dockerfile.ubuntu
- images/node/Dockerfile.centos
- images/node/Dockerfile.ubuntu
- images/pycharm/Dockerfile.centos
- images/pycharm/Dockerfile.ubuntu
- images/ruby/Dockerfile.centos
- images/ruby/Dockerfile.ubuntu
- images/vnc/Dockerfile.ubuntu
- images/webstorm/Dockerfile.centos
- images/webstorm/Dockerfile.ubuntu
Seems to cause the home directory to be set to `/home/1000` in C4D which breaks things @Emyrk 
Reverts coder/enterprise-images#133
> Revert "chore: switch from named to numeric uids"

- images/android/README.md
- images/dataSpell/Dockerfile.centos
- images/dataSpell/Dockerfile.ubuntu
- images/goland/README.md
- images/multieditor/Dockerfile.ubuntu
- images/vnc/README.md
- images/vnc/vnc/index.html
brings our DataSpell image up to date and attempts to resolve the CI build failures with an `apt-get update` addition to the `multieditor` image.
> Update data spell

- images/vnc/vnc/index.html
fixes connection issue between noVNC & the websocket. broken via https://github.com/coder/enterprise-images/pull/146/commits/abfa9f9113b2cdbf00ce5c289b12ab4793df58fa
i tested with my `ericpaulsen/vncdebug` image.
> fix: websockify path

- images/jupyter/Dockerfile.centos
- images/jupyter/Dockerfile.ubuntu
> fix: 500 on JupyterLab image

- images/clion/Dockerfile.centos
- images/clion/Dockerfile.ubuntu
- images/goland/Dockerfile.centos
- images/goland/Dockerfile.ubuntu
- images/intellij/Dockerfile.centos
- images/intellij/Dockerfile.ubuntu
- images/pycharm/Dockerfile.centos
- images/pycharm/Dockerfile.ubuntu
- images/webstorm/Dockerfile.centos
- images/webstorm/Dockerfile.ubuntu
This reverts commit 91bf78a9dc6bb18a205f475a141987de4f1eae9e.
Should un-break https://github.com/coder/v1/issues/12990
> Revert "chore: pin jetbrains IDE versions at 2021.x (#176)"

- images/rust/Dockerfile.centos
- images/rust/Dockerfile.ubuntu
- images/rust/README.md
- images/rust/rustup.sh
- scripts/images.sh
Fixes https://github.com/coder/enterprise-images/issues/189
> feat: add Rust image

- scripts/build_images.sh
- scripts/push_images.sh
we were using the same build file and id and overwriting the base image with minimal
Huge thanks to @jacobwgillespie for pointing it out.
> fix: fix pushing to correct repo

- scripts/build_images.sh
- scripts/push_images.sh
https://github.com/coder/enterprise-images/actions/runs/7542599337/job/20531773483
```
Usage:
depot <command> [flags]
depot [command]
```
> fix multiline check_dependencies invocation

- images/base/Dockerfile.ubuntu
- images/minimal/Dockerfile.ubuntu
- images/minimal/README.md
Fixes https://github.com/coder/enterprise-images/issues/269
> feat(image/base): add jq

- scripts/build_images.sh
- scripts/push_images.sh
Closes https://github.com/coder/enterprise-images/issues/272
> feat: add date-suffixed tags to built images

- images/base/ubuntu.Dockerfile
- images/minimal/ubuntu.Dockerfile
Cherry-picks commits from:
- https://github.com/coder/images/pull/289
- https://github.com/coder/images/pull/290
This is to work around issues with running CI from forks.
> fix: generate locales in minimal and base images
