configure/Dockerfile.ubuntu
configure/configure

Creates an example that uses `coder/configure` to install NVM
Adds a directory configure/ containing example files for publishing images that make use of Coder's configure feature. If an image contains a script called "configure" in the directory "/coder", it is automatically run during environment builds. The main use-case is
configurations that depend on the $HOME directory that cannot otherwise be added to an image's Dockerfile.
I created this publicly under my own account name at: https://hub.docker.com/repository/docker/vapurrmaid/coder

Add coder/configure example

---

images/base/Dockerfile.arch
images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu

We use `/etc/os-release` for OS info: https://github.com/cdr/c/blob/bc8fbd728f40a703ff39aa16b76709bd7fb1aa8c/rfcs/archive/0014-os-info.md

Remove lsb-release

---

images/base/Dockerfile.arch
images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu
images/java/Dockerfile.centos
images/java/Dockerfile.ubuntu

Another simple one, just installs the highest JDK version that both CentOS and Ubuntu had in their repositories (14). We could go through the trouble of downloading 15 and manually installing, but this just seemed easiest.

Add default java images

---

images/ruby/Dockerfile.centos
images/ruby/Dockerfile.ubuntu
images/ruby/install-ruby.sh

Adds images for ruby, using the distro's ruby packages. I initially wanted to do the installation via RVM so that they could easily switch versions, but I had a hell of a time getting RVM to install as root in Docker (seems to be a common problem.)
If anyone wants to take a better stab at this, be my guest.

Add default ruby images

---

.github/CODE_OF_CONDUCT.md

Adds a code of conduct to further our open source community in this repository. The email address used is `support@coder.com`

docs: Create code of conduct

---

README.md
images/base/README.md
images/configure/README.md
images/goland/README.md
images/golang/README.md
images/intellij/README.md
images/java/README.md
images/jupyter/README.md
images/multieditor/README.md
images/node/README.md
images/pycharm/README.md
images/webstorm/README.md

Adds a badge, wrapped by a url, for each of our images. The badge content is the number of dockerhub pulls, and the link is to the image's home on dockerhub.
Thought it might be nice to add badges for the images in this repository. Unsure if we should select a subset (and if so, what the subset criteria is), so I got the ball rolling with having them all up for now.

Add image-specific READMEs with dockerhub badges

---

images/pycharm/Dockerfile.centos
images/pycharm/Dockerfile.ubuntu

codercom/enterprise-pycharm installs [pycharm community](https://github.com/cdr/enterprise-images/blob/98c24a3f55e3a69249f6f9d0921a57bc767d6cc1/images/pycharm/Dockerfile.ubuntu#L8) then registers the application to our jetrbrains [`code-server` plugin](https://github.com/cdr/code-server/blob/v3.8.0/typings/pluginapi.d.ts)
with
```Dockerfile
RUN ln -s /opt/pycharm/bin/pycharm.sh /usr/bin/pycharm
```
However, the expected symlink for our jetbrains `code-server` plugin is `pycharm-community`
- `PyCharm Professional` will appear as the name of the application on the web client for what is really PyCharm Community. This will be fixed in versions > 1.15.x

fix(pycharm): Symlink pycharm -> pycharm-community

---

images/base/Dockerfile.arch
images/base/mirrorlist

* Switch from deprecated archlinux/base to archlinux/archlinux
* Pin a specific base image and repository snapshot, as recent
versions are inoperable under Coder due to a glibc upgrade
(https://bugs.archlinux.org/task/69563)

chore: pin archlinux package versions

---

.github/workflows/build.yaml

* Add scheduled build to run at 2am UTC
* Enable manual build trigger (workflow_dispatch)

chore: run and publish nightly image builds

---

images/base/Dockerfile.arch
images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu

* Reduce the number of layers in base images by consolidating
related build steps
* Switch from yum to its successor, dnf, in the centos base image
* Delete package cache after installation to reduce image size
* Use bash to run Dockerfile build commands in centos and ubuntu
* Sort package dependencies alphabetically

chore: optimize layers in base images

---

images/vnc/README.md

The docs discusses the general setup, but does not mention specific ports for Dev URLs or VNC, as that varies depending on the image configuration: https://coder.com/docs/guides/customization/vnc
This readme instructs the user how to use this VNC image with Coder

add readme for vnc image

---

images/vnc/Dockerfile.ubuntu
images/vnc/README.md
images/vnc/xfce4/helpers.rc
images/vnc/xfce4/xfconf/xfce-perchannel-xml/displays.xml
images/vnc/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
images/vnc/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

From the previous PR comments, it looked like VNC was configured for a 4k display. This made it difficult to browse from a laptop or even my ultrawide. These settings can always be configured by the user.
The installation method for Google Chrome led to errors. Since the desktop environment comes with firefox, I switched to that.
Also fixed a typo.

fixes to VNC image

---

.github/dependabot.yml

I have no idea if this will work, but it seems worth experimenting

chore: ignore minor/patch versions of official actions

---

package.json
yarn.lock

Install specific versions of dependencies, instead of using the
Node.js "compatible" semver syntax, to improve reproducibility
and consistency of dependency installs.

chore: do not install "compatible" versions

---

images/clion/Dockerfile.centos
images/clion/Dockerfile.ubuntu
images/clion/README.md
scripts/images.sh

This MR adds the Jetbrains clion image since clion is supported by coder and there has not been an image for it yet.
Sources: 
- https://coder.com/docs/coder/v1.19/workspaces/editors#jetbrains-ides-in-the-browser
- https://www.jetbrains.com/de-de/clion/

Added CLion image

---

images/java/Dockerfile.ubuntu

OpenJDK 14 appears to have disappeared from the Ubuntu focal
repository, so downgrade OpenJDK to the most recent LTS version,
which is version 11.

chore: downgrade openjdk from v14 to 11 (LTS)

---

images/golang/Dockerfile.centos
images/golang/Dockerfile.ubuntu

updating our golang images to include the latest stable version of go, `1.17.1`, based on [feedback from a hosted beta user](https://codercom.slack.com/archives/C02EK5ZB2R1/p1632339194053600). if there's any way for us to automate this process, let me know. I'd like to learn how to implement such automation into the images.

update go version to 1.17.1

---

.github/workflows/build.yaml

* Re-build images on Mondays, rather than daily
* Add a comment explaining rationale for the rebuild schedule

chore: re-build images weekly instead of daily

---

images/goland/Dockerfile.centos
images/goland/Dockerfile.ubuntu
images/goland/README.md

Using the GoLand JetBrains does not include Golang rendering a poor experience.  Adding enterprise-golang in lieu of multieditor image, and paste multieditor dependencies in GoLand image for JetBrains IDEs to continue to work in Projector (browser)

fix: missing golang from goland image

---

.github/workflows/build.yaml

The CentOS and Arch builds are currently broken, but this change is needed to unblock updates to the Ubuntu image.

chore: disable fail-fast for image build job

---

images/android/Dockerfile.ubuntu
images/base/Dockerfile.arch
images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu
images/clion/Dockerfile.centos
images/clion/Dockerfile.ubuntu
images/dataSpell/Dockerfile.centos
images/dataSpell/Dockerfile.ubuntu
images/goland/Dockerfile.centos
images/goland/Dockerfile.ubuntu
images/golang/Dockerfile.centos
images/golang/Dockerfile.ubuntu
images/intellij/Dockerfile.centos
images/intellij/Dockerfile.ubuntu
images/java/Dockerfile.centos
images/java/Dockerfile.ubuntu
images/jupyter/Dockerfile.centos
images/jupyter/Dockerfile.ubuntu
images/multieditor/Dockerfile.centos
images/multieditor/Dockerfile.ubuntu
images/node/Dockerfile.centos
images/node/Dockerfile.ubuntu
images/pycharm/Dockerfile.centos
images/pycharm/Dockerfile.ubuntu
images/ruby/Dockerfile.centos
images/ruby/Dockerfile.ubuntu
images/vnc/Dockerfile.ubuntu
images/webstorm/Dockerfile.centos
images/webstorm/Dockerfile.ubuntu

Clusters that have an admission controller that requires containers
to run as a non-root user need the default user of the image to be
declared as a numeric uid, so that the constraint can be applied
prior to starting the container.
Change "USER root" to "USER 0" and "USER coder" to "USER 1000"

chore: switch from named to numeric uids

---

images/vnc/Dockerfile.ubuntu

While this dependency doesn't seem necessary for our current builds, this was discovered to be a missing dependency (therefore breaking VNC) when this image is forked, or perhaps used with a different base image

add dbus-x11 to VNC image

---

images/base/Dockerfile.ubuntu

The runc included in the latest containerd.io package is incompatible with sysbox ATM.
https://github.com/nestybox/sysbox/issues/544

chore: downgrade runc version in ubuntu image

---

images/base/Dockerfile.ubuntu
images/base/containerd-pin

ensures that downstream images do not upgrade the `containerd` & `runc` versions

chore: pin containerd version

---

images/base/Dockerfile.centos
images/jupyter/Dockerfile.centos
scripts/images.sh

This PR makes the following changes to fix CentOS image builds:
- Move to CentOS 8 stream hosted on quay.io as a base, as CentOS 8 is EOL
- Install required python deps for Jupyter image
- Fix dependency ordering of images when building
- Downgrade containerd to version compatible with sysbox (ref: #158)

chore: fix centOS images

---

images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu

This will make unicode in terminals work (the `UTF-8` part).
We could also explicitly use a specific language like `en_US` instead of `C` (`en_US.UTF-8`) but for now I figure we keep the status quo there especially for base images.

Set LANG on base images

---

images/base/Dockerfile.centos
images/base/Dockerfile.ubuntu

Very useful for v1->v2 migration, so we want to have rsync widely available.

Add rsync to enterprise-base

---

.github/workflows/build.yaml

Node 12 for GitHub actions is deprecated and I confirmed this works for our packages.

use node 16 for GitHub actions

---

images/java/Dockerfile.ubuntu

Previous version of maven is no longer available from OSU.
```
Step 10/16 : RUN mkdir -p $MAVEN_HOME $MAVEN_HOME/ref   && echo "Downloading maven"   && curl -fsSL -o /tmp/apache-maven.tar.gz [https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz](https://apache.osuosl.org/maven/maven-3/$%7BMAVEN_VERSION%7D/binaries/apache-maven-$%7BMAVEN_VERSION%7D-bin.tar.gz)     && echo "Checking downloaded file hash"   && echo "${MAVEN_SHA512}  /tmp/apache-maven.tar.gz" | sha512sum -c -     && echo "Unzipping maven"   && tar -xzf /tmp/apache-maven.tar.gz -C $MAVEN_HOME --strip-components=1     && echo "Cleaning and setting links"   && rm -f /tmp/apache-maven.tar.gz   && ln -s $MAVEN_HOME/bin/mvn /usr/bin/mvn
---> Running in 49882ae5ae1e
Downloading …
```

fix(images/java): upgrade maven to 3.9.3

---

images/base/Dockerfile.ubuntu
images/base/docker.list
scripts/build_images.sh
scripts/push_images.sh

closes #185, closes #237 
> [!IMPORTANT]
> The build and push script requires depot CLI to be set up and fail if run locally and the depot is unavailable. We can add a fallback method to use docker CLI in a follow-up PR (docker needs a bit more work to push multi-arch image manifest)

feat: build multiarch images

---

scripts/push_images.sh

Now we only publish 'ubuntu' images and have deprecated `centos` in #238. So adding 'latest' as the tag will allow pulling with `docker pull codercom/enterprise-minimal` or `FROM codercom/enterprise-minimal`

feat: add `latest` tag

---

images/base/Dockerfile.ubuntu

I have tested this with a local build
```console
coder@ff439c7348c2:/$ which docker
/usr/bin/docker
coder@ff439c7348c2:/$ which docker-compose
/usr/bin/docker-compose
coder@ff439c7348c2:/$ docker-compose
Usage:  docker compose [OPTIONS] COMMAND
Define and run multi-container applications with Docker.
Options:
--ansi string                Control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
--compatibility              Run compose in backward compatibility mode
--dry-run                    Execute command in dry run mode
--env-file stringArray       Specify an alternate environment file.
-f, --file stringArray           Compose configuration files
--parallel int               Control max parallelism, -1 for unlimited (default -1)
--profile stringArray …
```

chore: use `docker-compose` binary from the `docker-compose-plugin` pkg

---

.github/workflows/build.yaml

As we are running the build on the depot.dev we probably do not need a paid GitHub Runner

ci: do not use the paid runner

---

images/base/Dockerfile.ubuntu
images/base/mirrorlist
images/minimal/Dockerfile.ubuntu

Format and optimize Dockerfiles to reduce size potentially. Combining `&& rm -rf /var/lib/apt/lists/*` with `apt-get install` reduces overall image size by reducing the size of the layer where packages are added.
This reduces the uncompressed image size for `codercom/enterprise-base` size from **1.08** GB to **1.02** GB

chore: format and optimize Dockerfiles

---

deprecated/vnc/Dockerfile.ubuntu
deprecated/vnc/turbovncserver-security.conf

> [!NOTE]
> This image is deprecated and no longer maintained; this fix is being pushed for illustrative purposes only.
Copying the content in this way resulted in raw `\n` sequences ending up in `/etc/turbovncserver-security.conf`. On later versions of Ubuntu (e.g. 22.04) this can cause the VNC desktop to require login, which will be impossible as the Coder user does not have a PAM password set.

fix(deprecated/vnc): fix broken turbovncserver-security.conf

---

README.md
images/base/docker.list
images/base/ubuntu.Dockerfile
images/minimal/ubuntu.Dockerfile

- Correct a typo in README.md
- Update Docker sources to use 'noble'
- Change base image from Ubuntu 22.04 to 'noble' 24.04

Switch images to Ubuntu `noble` 24.04

---

images/base/ubuntu.Dockerfile

After #277, the base images come with Python 3.12, which does not let us install a package in the base Python environment. [`pipx`](https://pipx.pypa.io/stable/) allows installing the packages by creating an isolated environment.

feat: add pipx to base image

---

images/java/ubuntu.Dockerfile

The CI was failing for the last 3 weeks because the old downloaded URL no longer resolves. 
https://github.com/coder/images/actions/runs/14698973787/job/41245005924
@jatcod3r I did not touch the Gradle version as I am not sure if there are any compatibility constraints.

chore: update maven version and download link
